### ISSUE TITLE
[Bug report]: Initializing SessionHostDbEntry causes a crash when adding a new session host

### ISSUE THREAD

**Issue by Smalls1652** [Smalls1652/SmallsOnline.AVD.ResourceManager#33]
### What kind of bug is this?

Crash

### If you selected "Other" in the previous section, what kind of bug is it?

N/A

### Describe the bug.

During the `UpdateAvdHostStatuses_Timer` function's execution, initializing a `SessionHostDbEntry` class throws an error to occur because a method could not b found.

### Logs (Optional)

```plain text
An exception of type 'System.MissingMethodException' occurred in SmallsOnline.AVD.ResourceManager.dll but was not handled in user code: 'Method not found: 'Azure.Core.ResourceIdentifier Azure.ResourceManager.Models.Resource.get_Id()'.'

   at SmallsOnline.AVD.ResourceManager.Lib.Models.Database.SessionHostDbEntry..ctor(VirtualMachineData virtualMachineData, HostPoolDbEntry avdHostPool, SessionHost avdSessionHostData, SessionHostDbEntry previousHostData) in src\SmallsOnline.AVD.ResourceManager.Lib\models\database\SessionHostDbEntry.cs:line 31
   at SmallsOnline.AVD.ResourceManager.Functions.UpdateAvdHostStatuses_Timer.Run(TimerInfo timer) in src\SmallsOnline.AVD.ResourceManager\functions\UpdateAvdHostStatuses_Timer.cs:line 100
   at Microsoft.Azure.Functions.Worker.Invocation.VoidMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in D:\a\1\s\src\DotNetWorker.Core\Invocation\VoidMethodInvoker.cs:line 23
   at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 31
   at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.<ExecuteAsync>d__4.MoveNext() in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 37
```

**Comment by Smalls1652** [comment]
Found the cause of the bug. Whenever I refactored the codebase and split certain classes from `SmallsOnline.AVD.ResourceManager` to `SmallsOnline.AVD.ResourceManager.Lib`, there was dependency mismatch between the two librarys:

https://github.com/Smalls1652/SmallsOnline.AVD.ResourceManager/blob/aa781324bc7f321ea66ca42f722c8caa306d91f3/src/SmallsOnline.AVD.ResourceManager/SmallsOnline.AVD.ResourceManager.csproj#L23-L24

https://github.com/Smalls1652/SmallsOnline.AVD.ResourceManager/blob/aa781324bc7f321ea66ca42f722c8caa306d91f3/src/SmallsOnline.AVD.ResourceManager.Lib/SmallsOnline.AVD.ResourceManager.Lib.csproj#L11-L13

Upgrading the dependencies in `SmallsOnline.AVD.ResourceManager` seems to have fixed the issue on my end.
